title: SIGINT.IN
author:
  name: neo

description: >
  rants informáticos

# Build settings
plugins:
  - jekyll-feed

tag_page_layout: tags
tag_page_dir: tag

# TODO: revisar esto, tiene potencial
#show_excerpts: true
